export const endpoints = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    google: '/auth/google',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    deleteAccount: '/auth/account',
  },
  discovery: {
    feed: '/discovery/feed',
    swipe: '/discovery/swipe',
    undo: '/discovery/undo',
  },
  matches: {
    list: '/matches',
    likesReceived: '/matches/likes-received',
    likesSent: '/matches/likes-sent',
    unmatch: (id: string) => `/matches/${id}/unmatch`,
    notifications: '/matches/notifications',
    readAllNotifications: '/matches/notifications/read-all',
  },
  users: {
    active: '/users/active',
    suggested: '/users/suggested',
    search: '/users/search',
    profile: (id: string) => `/users/${id}`,
    updateProfile: '/users/me',
    block: (id: string) => `/users/${id}/block`,
    unblock: (id: string) => `/users/${id}/unblock`,
    blockedList: '/users/blocked',
    report: (id: string) => `/users/${id}/report`,
  },
  moments: {
    list: '/moments',
    create: '/moments',
    like: (id: string) => `/moments/${id}/like`,
    comment: (id: string) => `/moments/${id}/comments`,
    detail: (id: string) => `/moments/${id}`,
  },
  chats: {
    list: '/chats',
    messages: (id: string) => `/chats/${id}/messages`,
    send: (id: string) => `/chats/${id}/messages`,
  },
  groups: {
    list: '/groups',
    create: '/groups',
    invitePreview: (code: string) => `/groups/invite/${code}`,
    join: (code: string) => `/groups/invite/${code}/join`,
    addMember: (id: string) => `/groups/${id}/add-member`,
    getInvites: '/groups/invites',
    acceptInvite: (id: string) => `/groups/invites/${id}/accept`,
    declineInvite: (id: string) => `/groups/invites/${id}/decline`,
    messages: (id: string) => `/groups/${id}/messages`,
    info: (id: string) => `/groups/${id}/info`,
    delete: (id: string) => `/groups/${id}`,
    leave: (id: string) => `/groups/${id}/leave`,
  },
  moderation: {
    report: '/moderation/report',
    actions: '/moderation/actions',
  },
  onboarding: '/onboarding/complete',
} as const;
